apiVersion: v1
kind: Namespace
metadata:
  name: covid-army

---
apiVersion: v1
kind: Service
metadata:
  name: covid-army
spec:
  type: NodePort
  selector:
    app: covid-army
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-army
spec:
  selector:
    matchLabels:
      app: covid-army
  replicas: 1
  template:
    metadata:
      labels:
        app: covid-army
    spec:
      containers:
        - name: covid-army
          image: docker.io/covidarmy/covid-army-backend:latest
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: covid-army-env
                  key: MONGO_URI
            - name: BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: covid-army-env
                  key: BEARER_TOKEN

          ports:
            - containerPort: 4000
              protocol: "TCP"
